language: haxe

haxe:
  - "3.4.4"

addons:
  chrome: stable
  
install:
  - haxelib install munit
  - haxelib install mcover
  - haxelib install hamcrest
  
script:
  - haxelib run munit gen
  - haxelib run munit test -browser "google-chrome-stable --headless --no-sandbox" -kill-browser
  
cache:
  directories:
    - $HOME/haxe/lib